import type { Event, HijriMonthOverride } from "@shared/schema";
import { hijriMonthNames } from "@shared/schema";
import { hijriToGregorian, getCurrentHijriYear } from "./hijri-utils";

const HIJRI_MONTH_START_PREFIX = "hijri_month_start_";

export function generateHijriMonthStartEvents(
  hijriYear: number,
  overrides: HijriMonthOverride[]
): Event[] {
  const events: Event[] = [];

  for (let month = 1; month <= 12; month++) {
    const gregorianDate = hijriToGregorian(
      { year: hijriYear, month, day: 1 },
      overrides
    );

    const event: Event = {
      id: `${HIJRI_MONTH_START_PREFIX}${hijriYear}_${month}`,
      title: `بداية شهر ${hijriMonthNames[month - 1]}`,
      description: `أول يوم من شهر ${hijriMonthNames[month - 1]} ${hijriYear} هـ`,
      dateType: "hijri",
      gregorianDate: gregorianDate.toISOString().split("T")[0],
      hijriYear: hijriYear,
      hijriMonth: month,
      hijriDay: 1,
      isAnnual: false,
      color: "green",
      isAutoGenerated: true,
      autoGeneratedType: "hijri_month_start",
    };

    events.push(event);
  }

  return events;
}

export function updateHijriMonthStartEvents(
  existingEvents: Event[],
  overrides: HijriMonthOverride[]
): { updatedEvents: Event[]; eventsToUpdate: Event[] } {
  const eventsToUpdate: Event[] = [];
  const updatedEvents = existingEvents.map((event) => {
    if (
      event.isAutoGenerated &&
      event.autoGeneratedType === "hijri_month_start"
    ) {
      const newGregorianDate = hijriToGregorian(
        {
          year: event.hijriYear,
          month: event.hijriMonth,
          day: 1,
        },
        overrides
      );

      const newDateStr = newGregorianDate.toISOString().split("T")[0];
      if (event.gregorianDate !== newDateStr) {
        const updated = {
          ...event,
          gregorianDate: newDateStr,
        };
        eventsToUpdate.push(updated);
        return updated;
      }
    }
    return event;
  });

  return { updatedEvents, eventsToUpdate };
}

export function getAutoGeneratedEventIds(events: Event[]): string[] {
  return events
    .filter((e) => e.isAutoGenerated && e.autoGeneratedType === "hijri_month_start")
    .map((e) => e.id);
}

export function isAutoGeneratedEvent(event: Event): boolean {
  return event.isAutoGenerated === true;
}

export function getYearsWithAutoEvents(events: Event[]): number[] {
  const years = new Set<number>();
  events.forEach((event) => {
    if (event.isAutoGenerated && event.autoGeneratedType === "hijri_month_start") {
      years.add(event.hijriYear);
    }
  });
  return Array.from(years);
}

export function generateMultiYearHijriEvents(
  startYear: number,
  endYear: number,
  overrides: HijriMonthOverride[]
): Event[] {
  const allEvents: Event[] = [];
  for (let year = startYear; year <= endYear; year++) {
    allEvents.push(...generateHijriMonthStartEvents(year, overrides));
  }
  return allEvents;
}
