// في ملف جديد: event-sync.ts

export async function ensureHijriEventsGenerated(
  storage: YourStorageType,
  overrides: HijriMonthOverride[]
): Promise<void> {
  const currentYear = getCurrentHijriYear();
  const existingEvents = await storage.getAllEvents();
  
  // فحص: هل تم توليد أحداث هذا العام من قبل؟
  const hasEventsForCurrentYear = existingEvents.some(
    e => e.isAutoGenerated && 
    e.autoGeneratedType === "hijri_month_start" && 
    e.hijriYear === currentYear
  );
  
  if (hasEventsForCurrentYear) {
    console.log("Events already generated for year", currentYear);
    return; // لا تولد مرة أخرى
  }
  
  // توليد الأحداث فقط إذا لم تكن موجودة
  const newEvents = generateHijriMonthStartEvents(currentYear, overrides);
  await storage.addEvents(newEvents);
}
