import type { Event } from "@shared/schema";

/**
 * حذف الأحداث المكررة
 */
export function removeDuplicateEvents(events: Event[]): {
  uniqueEvents: Event[];
  duplicateIds: string[];
} {
  const seen = new Map<string, Event>();
  const duplicateIds: string[] = [];
  
  events.forEach(event => {
    if (event.isAutoGenerated && event.autoGeneratedType === "hijri_month_start") {
      const key = `${event.hijriYear}-${event.hijriMonth}`;
      
      if (seen.has(key)) {
        duplicateIds.push(event.id);
      } else {
        seen.set(key, event);
      }
    } else {
      // الأحداث العادية (غير المولدة تلقائياً) نحتفظ بها دائماً
      seen.set(event.id, event);
    }
  });
  
  return {
    uniqueEvents: Array.from(seen.values()),
    duplicateIds
  };
}
