import type { HijriMonthOverride, Event } from "@shared/schema";

/**
 * دمج التعديلات المحلية والبعيدة
 * يختار التعديل الأحدث بناءً على timestamp
 */
export async function syncOverrides(
  localOverrides: HijriMonthOverride[],
  remoteOverrides: HijriMonthOverride[]
): Promise<HijriMonthOverride[]> {
  const merged = new Map<string, HijriMonthOverride>();
  
  [...localOverrides, ...remoteOverrides].forEach(override => {
    const key = `${override.year}-${override.month}`;
    const existing = merged.get(key);
    
    if (!existing || (override.timestamp || 0) > (existing.timestamp || 0)) {
      merged.set(key, override);
    }
  });
  
  return Array.from(merged.values());
}

/**
 * فحص إذا كانت الأحداث موجودة لسنة معينة
 */
export function hasEventsForYear(
  events: Event[],
  year: number
): boolean {
  return events.some(
    e => e.isAutoGenerated && 
    e.autoGeneratedType === "hijri_month_start" && 
    e.hijriYear === year
  );
}
