import { create } from "zustand";
import type { Event, HijriMonthOverride, Settings, BackupData } from "@shared/schema";
import { apiRequest, queryClient } from "@/lib/queryClient";
import {
  generateMultiYearHijriEvents,
  updateHijriMonthStartEvents,
  isAutoGeneratedEvent,
} from "@/lib/auto-events";
import { getCurrentHijriYear } from "@/lib/hijri-utils";

interface CalendarState {
  events: Event[];
  hijriOverrides: HijriMonthOverride[];
  settings: Settings;
  currentDate: Date;
  selectedDate: Date | null;
  view: "monthly" | "weekly" | "yearly";
  isLoading: boolean;
  
  setCurrentDate: (date: Date) => void;
  setSelectedDate: (date: Date | null) => void;
  setView: (view: "monthly" | "weekly" | "yearly") => void;
  
  loadData: () => Promise<void>;
  
  addEvent: (event: Omit<Event, "id">) => Promise<void>;
  updateEvent: (id: string, event: Partial<Event>) => Promise<void>;
  deleteEvent: (id: string) => Promise<void>;
  importEvents: (events: Partial<Event>[]) => Promise<number>;
  
  addHijriOverride: (override: Omit<HijriMonthOverride, "id">) => Promise<void>;
  deleteHijriOverride: (id: string) => Promise<void>;
  
  updateSettings: (settings: Partial<Settings>) => Promise<void>;
  
  restoreBackup: (data: BackupData) => Promise<void>;
  clearAllData: () => Promise<void>;
  
  generateAutoEvents: () => Promise<void>;
  refreshAutoEvents: () => Promise<void>;
}

export const useCalendarStore = create<CalendarState>((set, get) => ({
  events: [],
  hijriOverrides: [],
  settings: {
    hijriEnabled: true,
    hijriReference: "khamenei",
    defaultView: "monthly",
    numeralSystem: "arabic",
    notificationsEnabled: true,
  },
  currentDate: new Date(),
  selectedDate: null,
  view: "monthly",
  isLoading: true,

  setCurrentDate: (date) => set({ currentDate: date }),
  setSelectedDate: (date) => set({ selectedDate: date }),
  setView: (view) => set({ view }),

  loadData: async () => {
    set({ isLoading: true });
    try {
      const [eventsRes, overridesRes, settingsRes] = await Promise.all([
        apiRequest("GET", "/api/events"),
        apiRequest("GET", "/api/hijri-overrides"),
        apiRequest("GET", "/api/settings"),
      ]);
      
      const events = await eventsRes.json();
      const hijriOverrides = await overridesRes.json();
      const settings = await settingsRes.json();

      set({
        events,
        hijriOverrides,
        settings,
        view: settings.defaultView || "monthly",
        isLoading: false,
      });
    } catch (error) {
      console.error("Failed to load data:", error);
      set({ isLoading: false });
    }
  },

  addEvent: async (eventData) => {
    const res = await apiRequest("POST", "/api/events", eventData);
    const newEvent = await res.json();
    set((state) => ({ events: [...state.events, newEvent] }));
  },

  updateEvent: async (id, eventData) => {
    const res = await apiRequest("PUT", `/api/events/${id}`, eventData);
    const updatedEvent = await res.json();
    set((state) => ({
      events: state.events.map((e) => (e.id === id ? updatedEvent : e)),
    }));
  },

  deleteEvent: async (id) => {
    await apiRequest("DELETE", `/api/events/${id}`);
    set((state) => ({
      events: state.events.filter((e) => e.id !== id),
    }));
  },

  importEvents: async (partialEvents) => {
    const { hijriOverrides } = get();
    let importedCount = 0;

    for (const partial of partialEvents) {
      if (!partial.title || !partial.gregorianDate) continue;

      const date = new Date(partial.gregorianDate);
      const { gregorianToHijri } = await import("@/lib/hijri-utils");
      const hijri = gregorianToHijri(date, hijriOverrides);

      const eventData = {
        title: partial.title,
        description: partial.description || "",
        dateType: partial.dateType || "gregorian",
        gregorianDate: partial.gregorianDate,
        hijriYear: hijri.year,
        hijriMonth: hijri.month,
        hijriDay: hijri.day,
        isAnnual: partial.isAnnual || false,
        color: partial.color || "primary",
        isAutoGenerated: false,
      };

      const res = await apiRequest("POST", "/api/events", eventData);
      const newEvent = await res.json();
      set((state) => ({ events: [...state.events, newEvent] }));
      importedCount++;
    }

    return importedCount;
  },

  addHijriOverride: async (overrideData) => {
    const res = await apiRequest("POST", "/api/hijri-overrides", overrideData);
    const newOverride = await res.json();
    const newOverrides = [...get().hijriOverrides, newOverride];
    set({ hijriOverrides: newOverrides });
    
    await get().refreshAutoEvents();
  },

  deleteHijriOverride: async (id) => {
    await apiRequest("DELETE", `/api/hijri-overrides/${id}`);
    const newOverrides = get().hijriOverrides.filter((o) => o.id !== id);
    set({ hijriOverrides: newOverrides });
    
    await get().refreshAutoEvents();
  },

  updateSettings: async (newSettings) => {
    const res = await apiRequest("PUT", "/api/settings", newSettings);
    const updated = await res.json();
    set({ settings: updated });
  },

  restoreBackup: async (data) => {
    // This would need a bulk API endpoint for efficiency
    // For now, keeping it local or informing user it needs backend support
    console.warn("Restore backup needs backend implementation for full sync");
  },

  clearAllData: async () => {
    // This would need a bulk delete API
    console.warn("Clear all data needs backend implementation for full sync");
  },

  generateAutoEvents: async () => {
    const { events, hijriOverrides } = get();
    
    const existingAutoEvents = events.filter(
      (e) => e.isAutoGenerated && e.autoGeneratedType === "hijri_month_start"
    );

    const currentYear = getCurrentHijriYear();
    const newAutoEvents = generateMultiYearHijriEvents(
      currentYear,
      currentYear + 1,
      hijriOverrides
    );

    for (const event of newAutoEvents) {
      const existing = existingAutoEvents.find((e) => e.id === event.id);
      if (existing) {
        if (existing.gregorianDate !== event.gregorianDate) {
          const res = await apiRequest("PUT", `/api/events/${existing.id}`, event);
          const updated = await res.json();
          set((state) => ({
            events: state.events.map(e => e.id === updated.id ? updated : e)
          }));
        }
      } else {
        const res = await apiRequest("POST", "/api/events", event);
        const added = await res.json();
        set((state) => ({ events: [...state.events, added] }));
      }
    }
  },

  refreshAutoEvents: async () => {
    const { events, hijriOverrides } = get();
    
    const { updatedEvents, eventsToUpdate } = updateHijriMonthStartEvents(
      events,
      hijriOverrides
    );

    for (const event of eventsToUpdate) {
      await apiRequest("PUT", `/api/events/${event.id}`, event);
    }

    if (eventsToUpdate.length > 0) {
      // Re-fetch all events to ensure consistency
      const res = await apiRequest("GET", "/api/events");
      const latestEvents = await res.json();
      set({ events: latestEvents });
    }
  },
}));
