import { create } from "zustand";
import type { Event, HijriMonthOverride, Settings, BackupData } from "@shared/schema";
import * as db from "@/lib/db";
import {
  generateMultiYearHijriEvents,
  updateHijriMonthStartEvents,
  isAutoGeneratedEvent,
} from "@/lib/auto-events";
import { getCurrentHijriYear } from "@/lib/hijri-utils";

interface CalendarState {
  events: Event[];
  hijriOverrides: HijriMonthOverride[];
  settings: Settings;
  currentDate: Date;
  selectedDate: Date | null;
  view: "monthly" | "weekly" | "yearly";
  isLoading: boolean;
  
  setCurrentDate: (date: Date) => void;
  setSelectedDate: (date: Date | null) => void;
  setView: (view: "monthly" | "weekly" | "yearly") => void;
  
  loadData: () => Promise<void>;
  
  addEvent: (event: Event) => Promise<void>;
  updateEvent: (event: Event) => Promise<void>;
  deleteEvent: (id: string) => Promise<void>;
  importEvents: (events: Partial<Event>[]) => Promise<number>;
  
  addHijriOverride: (override: HijriMonthOverride) => Promise<void>;
  deleteHijriOverride: (id: string) => Promise<void>;
  
  updateSettings: (settings: Partial<Settings>) => Promise<void>;
  
  restoreBackup: (data: BackupData) => Promise<void>;
  clearAllData: () => Promise<void>;
  
  generateAutoEvents: () => Promise<void>;
  refreshAutoEvents: () => Promise<void>;
}

export const useCalendarStore = create<CalendarState>((set, get) => ({
  events: [],
  hijriOverrides: [],
  settings: {
    hijriEnabled: true,
    hijriReference: "khamenei",
    defaultView: "monthly",
    numeralSystem: "arabic",
    notificationsEnabled: true,
  },
  currentDate: new Date(),
  selectedDate: null,
  view: "monthly",
  isLoading: true,

  setCurrentDate: (date) => set({ currentDate: date }),
  setSelectedDate: (date) => set({ selectedDate: date }),
  setView: (view) => set({ view }),

  loadData: async () => {
    set({ isLoading: true });
    try {
      const [events, hijriOverrides, settings] = await Promise.all([
        db.getAllEvents(),
        db.getAllHijriOverrides(),
        db.initializeSettings(),
      ]);
      set({
        events,
        hijriOverrides,
        settings,
        view: settings.defaultView,
        isLoading: false,
      });
    } catch (error) {
      console.error("Failed to load data:", error);
      set({ isLoading: false });
    }
  },

  addEvent: async (event) => {
    await db.addEvent(event);
    set((state) => ({ events: [...state.events, event] }));
  },

  updateEvent: async (event) => {
    await db.updateEvent(event);
    set((state) => ({
      events: state.events.map((e) => (e.id === event.id ? event : e)),
    }));
  },

  deleteEvent: async (id) => {
    await db.deleteEvent(id);
    set((state) => ({
      events: state.events.filter((e) => e.id !== id),
    }));
  },

  importEvents: async (partialEvents) => {
    const { hijriOverrides } = get();
    let importedCount = 0;

    for (const partial of partialEvents) {
      if (!partial.title || !partial.gregorianDate) continue;

      const date = new Date(partial.gregorianDate);
      const { gregorianToHijri } = await import("@/lib/hijri-utils");
      const hijri = gregorianToHijri(date, hijriOverrides);

      const event: Event = {
        id: crypto.randomUUID(),
        title: partial.title,
        description: partial.description || "",
        dateType: partial.dateType || "gregorian",
        gregorianDate: partial.gregorianDate,
        hijriYear: hijri.year,
        hijriMonth: hijri.month,
        hijriDay: hijri.day,
        isAnnual: partial.isAnnual || false,
        color: partial.color || "primary",
        isAutoGenerated: false,
      };

      await db.addEvent(event);
      set((state) => ({ events: [...state.events, event] }));
      importedCount++;
    }

    return importedCount;
  },

  addHijriOverride: async (override) => {
    await db.addHijriOverride(override);
    const newOverrides = [...get().hijriOverrides, override];
    set({ hijriOverrides: newOverrides });
    
    await get().refreshAutoEvents();
  },

  deleteHijriOverride: async (id) => {
    await db.deleteHijriOverride(id);
    const newOverrides = get().hijriOverrides.filter((o) => o.id !== id);
    set({ hijriOverrides: newOverrides });
    
    await get().refreshAutoEvents();
  },

  updateSettings: async (newSettings) => {
    const { settings } = get();
    const updated = { ...settings, ...newSettings };
    await db.saveSettings(updated);
    set({ settings: updated });
  },

  restoreBackup: async (data) => {
    await db.clearAllEvents();
    await db.clearAllHijriOverrides();
    
    for (const event of data.events) {
      await db.addEvent(event);
    }
    
    for (const override of data.hijriOverrides) {
      await db.addHijriOverride(override);
    }
    
    if (data.settings) {
      await db.saveSettings(data.settings);
    }
    
    set({
      events: data.events,
      hijriOverrides: data.hijriOverrides,
      settings: data.settings || get().settings,
    });
  },

  clearAllData: async () => {
    await db.clearAllEvents();
    await db.clearAllHijriOverrides();
    set({ events: [], hijriOverrides: [] });
  },

  generateAutoEvents: async () => {
    const { events, hijriOverrides } = get();
    
    const existingAutoIds = new Set(
      events
        .filter((e) => e.isAutoGenerated && e.autoGeneratedType === "hijri_month_start")
        .map((e) => e.id)
    );

    const currentYear = getCurrentHijriYear();
    const newAutoEvents = generateMultiYearHijriEvents(
      currentYear,
      currentYear + 1,
      hijriOverrides
    );

    const eventsToAdd: Event[] = [];
    for (const event of newAutoEvents) {
      if (!existingAutoIds.has(event.id)) {
        await db.addEvent(event);
        eventsToAdd.push(event);
      }
    }

    if (eventsToAdd.length > 0) {
      set((state) => ({ events: [...state.events, ...eventsToAdd] }));
    }
  },

  refreshAutoEvents: async () => {
    const { events, hijriOverrides } = get();
    
    const { updatedEvents, eventsToUpdate } = updateHijriMonthStartEvents(
      events,
      hijriOverrides
    );

    for (const event of eventsToUpdate) {
      await db.updateEvent(event);
    }

    if (eventsToUpdate.length > 0) {
      set({ events: updatedEvents });
    }
  },
}));
