import { z } from "zod";
import { pgTable, serial, text, boolean, integer, timestamp, pgEnum, unique } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";

// ==================== Zod Schemas (Client-side validation) ====================

export const calendarTypeSchema = z.enum(["gregorian", "hijri"]);
export type CalendarType = z.infer<typeof calendarTypeSchema>;

export const hijriReferenceSchema = z.enum(["khamenei", "manual"]);
export type HijriReference = z.infer<typeof hijriReferenceSchema>;

export const eventColorSchema = z.enum([
  "primary",
  "red",
  "orange", 
  "yellow",
  "green",
  "blue",
  "purple",
  "pink",
]);
export type EventColor = z.infer<typeof eventColorSchema>;

export const recurrenceTypeSchema = z.enum(["none", "daily", "weekly", "monthly", "yearly"]);
export type RecurrenceType = z.infer<typeof recurrenceTypeSchema>;

export const eventSchema = z.object({
  id: z.string(),
  title: z.string().min(1, "العنوان مطلوب"),
  description: z.string().optional(),
  dateType: calendarTypeSchema,
  gregorianDate: z.string(),
  hijriYear: z.number(),
  hijriMonth: z.number(),
  hijriDay: z.number(),
  isAnnual: z.boolean().default(false),
  color: eventColorSchema.default("primary"),
  notifyDaysBefore: z.number().optional(),
  isAutoGenerated: z.boolean().default(false),
  autoGeneratedType: z.string().optional(),
  fileId: z.number().optional(),
  recurrenceType: recurrenceTypeSchema.default("none"),
  recurrenceEndDate: z.string().optional(),
  recurrenceInterval: z.number().optional().default(1),
});

export type Event = z.infer<typeof eventSchema>;

export const insertEventSchema = eventSchema.omit({ id: true });
export type InsertEvent = z.infer<typeof insertEventSchema>;

export const hijriMonthOverrideSchema = z.object({
  id: z.string(),
  hijriYear: z.number(),
  hijriMonth: z.number(),
  gregorianStartDate: z.string(),
});

export type HijriMonthOverride = z.infer<typeof hijriMonthOverrideSchema>;

export const insertHijriMonthOverrideSchema = hijriMonthOverrideSchema.omit({ id: true });
export type InsertHijriMonthOverride = z.infer<typeof insertHijriMonthOverrideSchema>;

export const numeralSystemSchema = z.enum(["arabic", "hindi"]);
export type NumeralSystem = z.infer<typeof numeralSystemSchema>;

export const settingsSchema = z.object({
  hijriEnabled: z.boolean().default(true),
  hijriReference: hijriReferenceSchema.default("khamenei"),
  defaultView: z.enum(["monthly", "weekly", "yearly"]).default("monthly"),
  numeralSystem: numeralSystemSchema.default("arabic"),
  notificationsEnabled: z.boolean().default(true),
});

export type Settings = z.infer<typeof settingsSchema>;

// ==================== Constants ====================

export const hijriMonthNames = [
  "محرم",
  "صفر",
  "ربيع الأول",
  "ربيع الثاني",
  "جمادى الأولى",
  "جمادى الآخرة",
  "رجب",
  "شعبان",
  "رمضان",
  "شوال",
  "ذو القعدة",
  "ذو الحجة",
] as const;

export const gregorianMonthNames = [
  "كانون الثاني",
  "شباط",
  "آذار",
  "نيسان",
  "أيار",
  "حزيران",
  "تموز",
  "آب",
  "أيلول",
  "تشرين الأول",
  "تشرين الثاني",
  "كانون الأول",
] as const;

export const weekDayNames = [
  "الأحد",
  "الإثنين",
  "الثلاثاء",
  "الأربعاء",
  "الخميس",
  "الجمعة",
  "السبت",
] as const;

export const eventColorNames: Record<EventColor, string> = {
  primary: "أزرق داكن",
  red: "أحمر",
  orange: "برتقالي",
  yellow: "أصفر",
  green: "أخضر",
  blue: "أزرق",
  purple: "بنفسجي",
  pink: "وردي",
};

export const recurrenceTypeNames: Record<RecurrenceType, string> = {
  none: "بدون تكرار",
  daily: "يومي",
  weekly: "أسبوعي",
  monthly: "شهري",
  yearly: "سنوي",
};

export const pdfExportOptionsSchema = z.object({
  dateRange: z.object({
    start: z.string(),
    end: z.string(),
  }),
  displayType: z.enum(["gregorian", "hijri", "both"]),
});

export type PDFExportOptions = z.infer<typeof pdfExportOptionsSchema>;

export const backupDataSchema = z.object({
  version: z.string(),
  exportDate: z.string(),
  events: z.array(eventSchema),
  hijriOverrides: z.array(hijriMonthOverrideSchema),
  settings: settingsSchema,
});

export type BackupData = z.infer<typeof backupDataSchema>;

// ==================== Drizzle Enums ====================

export const userRoleEnum = pgEnum("user_role", ["admin", "user"]);
export const calendarTypeEnum = pgEnum("calendar_type", ["gregorian", "hijri"]);
export const eventColorEnum = pgEnum("event_color", ["primary", "red", "orange", "yellow", "green", "blue", "purple", "pink"]);
export const hijriReferenceEnum = pgEnum("hijri_reference", ["khamenei", "manual"]);
export const defaultViewEnum = pgEnum("default_view", ["monthly", "weekly", "yearly"]);
export const numeralSystemEnum = pgEnum("numeral_system", ["arabic", "hindi"]);
export const fileRoleEnum = pgEnum("file_role", ["manager", "deputy", "member"]);
export const recurrenceTypeEnum = pgEnum("recurrence_type", ["none", "daily", "weekly", "monthly", "yearly"]);
export const taskStatusEnum = pgEnum("task_status", ["pending", "in_progress", "completed", "cancelled"]);
export const notificationTypeEnum = pgEnum("notification_type", ["event_reminder", "task_assigned", "task_updated", "file_invitation", "general"]);
export const attendanceStatusEnum = pgEnum("attendance_status", ["present", "absent", "excused", "late"]);

// ==================== Drizzle Tables ====================

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  displayName: text("display_name"),
  description: text("description"),
  role: userRoleEnum("role").notNull().default("user"),
  isActive: boolean("is_active").notNull().default(true),
  canCreateEvents: boolean("can_create_events").notNull().default(false),
  canEditEvents: boolean("can_edit_events").notNull().default(false),
  canDeleteEvents: boolean("can_delete_events").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const events = pgTable("events", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description"),
  dateType: calendarTypeEnum("date_type").notNull().default("gregorian"),
  gregorianDate: text("gregorian_date").notNull(),
  hijriYear: integer("hijri_year").notNull(),
  hijriMonth: integer("hijri_month").notNull(),
  hijriDay: integer("hijri_day").notNull(),
  isAnnual: boolean("is_annual").notNull().default(false),
  color: eventColorEnum("color").notNull().default("primary"),
  notifyDaysBefore: integer("notify_days_before"),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  autoGeneratedType: text("auto_generated_type"),
  fileId: integer("file_id").references(() => files.id),
  createdBy: integer("created_by").references(() => users.id),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  recurrenceType: recurrenceTypeEnum("recurrence_type").notNull().default("none"),
  recurrenceEndDate: text("recurrence_end_date"),
  recurrenceInterval: integer("recurrence_interval"),
});

export const hijriOverrides = pgTable("hijri_overrides", {
  id: serial("id").primaryKey(),
  hijriYear: integer("hijri_year").notNull(),
  hijriMonth: integer("hijri_month").notNull(),
  gregorianStartDate: text("gregorian_start_date").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const settings = pgTable("settings", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id).notNull().unique(),
  hijriEnabled: boolean("hijri_enabled").notNull().default(true),
  hijriReference: hijriReferenceEnum("hijri_reference").notNull().default("khamenei"),
  defaultView: defaultViewEnum("default_view").notNull().default("monthly"),
  numeralSystem: numeralSystemEnum("numeral_system").notNull().default("arabic"),
  notificationsEnabled: boolean("notifications_enabled").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const files = pgTable("files", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  createdBy: integer("created_by").references(() => users.id),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const fileMemberships = pgTable("file_memberships", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id).notNull(),
  fileId: integer("file_id").references(() => files.id).notNull(),
  role: fileRoleEnum("role").notNull().default("member"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const tasks = pgTable("tasks", {
  id: serial("id").primaryKey(),
  eventId: integer("event_id").references(() => events.id).notNull(),
  title: text("title").notNull(),
  description: text("description"),
  assignedTo: integer("assigned_to").references(() => users.id),
  status: taskStatusEnum("status").notNull().default("pending"),
  dueDate: text("due_date"),
  createdBy: integer("created_by").references(() => users.id),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const attachments = pgTable("attachments", {
  id: serial("id").primaryKey(),
  eventId: integer("event_id").references(() => events.id).notNull(),
  fileName: text("file_name").notNull(),
  objectPath: text("object_path").notNull(),
  fileSize: integer("file_size").notNull(),
  contentType: text("content_type").notNull(),
  uploadedBy: integer("uploaded_by").references(() => users.id),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const notifications = pgTable("notifications", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id).notNull(),
  type: notificationTypeEnum("type").notNull().default("general"),
  title: text("title").notNull(),
  message: text("message").notNull(),
  link: text("link"),
  isRead: boolean("is_read").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const userNotificationSettings = pgTable("user_notification_settings", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id).notNull().unique(),
  emailNotifications: boolean("email_notifications").notNull().default(true),
  inAppNotifications: boolean("in_app_notifications").notNull().default(true),
  eventReminders: boolean("event_reminders").notNull().default(true),
  taskNotifications: boolean("task_notifications").notNull().default(true),
  email: text("email"),
  reminderDaysBefore: integer("reminder_days_before").notNull().default(1),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const attendance = pgTable("attendance", {
  id: serial("id").primaryKey(),
  eventId: integer("event_id").references(() => events.id).notNull(),
  userId: integer("user_id").references(() => users.id).notNull(),
  status: attendanceStatusEnum("status").notNull().default("present"),
  notes: text("notes"),
  markedAt: timestamp("marked_at").notNull().defaultNow(),
  markedBy: integer("marked_by").references(() => users.id),
}, (table) => ({
  uniqueEventUser: unique().on(table.eventId, table.userId),
}));

export const messages = pgTable("messages", {
  id: serial("id").primaryKey(),
  fileId: integer("file_id").references(() => files.id).notNull(),
  userId: integer("user_id").references(() => users.id).notNull(),
  content: text("content").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const documents = pgTable("documents", {
  id: serial("id").primaryKey(),
  fileId: integer("file_id").references(() => files.id).notNull(),
  name: text("name").notNull(),
  description: text("description"),
  objectPath: text("object_path").notNull(),
  fileSize: integer("file_size"),
  contentType: text("content_type"),
  uploadedBy: integer("uploaded_by").references(() => users.id),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ==================== Drizzle Insert Schemas ====================

export const insertUserSchema = createInsertSchema(users).omit({ 
  id: true, 
  createdAt: true 
});

export const insertEventDbSchema = createInsertSchema(events).omit({ 
  id: true, 
  createdAt: true 
});

export const insertHijriOverrideDbSchema = createInsertSchema(hijriOverrides).omit({ 
  id: true, 
  createdAt: true 
});

export const insertSettingsDbSchema = createInsertSchema(settings).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});

export const insertFileSchema = createInsertSchema(files).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});

export const insertFileMembershipSchema = createInsertSchema(fileMemberships).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});

export const insertTaskSchema = createInsertSchema(tasks).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});

export const insertAttachmentSchema = createInsertSchema(attachments).omit({ 
  id: true, 
  createdAt: true 
});

export const insertNotificationSchema = createInsertSchema(notifications).omit({ 
  id: true, 
  createdAt: true 
});

export const insertUserNotificationSettingsSchema = createInsertSchema(userNotificationSettings).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});

export const insertAttendanceSchema = createInsertSchema(attendance).omit({ 
  id: true, 
  markedAt: true 
});

export const insertMessageSchema = createInsertSchema(messages).omit({ 
  id: true, 
  createdAt: true 
});

export const insertDocumentSchema = createInsertSchema(documents).omit({ 
  id: true, 
  createdAt: true 
});

// ==================== Drizzle Types ====================

export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;

export type EventDb = typeof events.$inferSelect;
export type InsertEventDb = z.infer<typeof insertEventDbSchema>;

export type HijriOverrideDb = typeof hijriOverrides.$inferSelect;
export type InsertHijriOverrideDb = z.infer<typeof insertHijriOverrideDbSchema>;

export type SettingsDb = typeof settings.$inferSelect;
export type InsertSettingsDb = z.infer<typeof insertSettingsDbSchema>;

export type FileDb = typeof files.$inferSelect;
export type InsertFile = z.infer<typeof insertFileSchema>;

export type FileMembershipDb = typeof fileMemberships.$inferSelect;
export type InsertFileMembership = z.infer<typeof insertFileMembershipSchema>;

export type TaskDb = typeof tasks.$inferSelect;
export type InsertTask = z.infer<typeof insertTaskSchema>;

export type AttachmentDb = typeof attachments.$inferSelect;
export type InsertAttachment = z.infer<typeof insertAttachmentSchema>;

export type NotificationDb = typeof notifications.$inferSelect;
export type InsertNotification = z.infer<typeof insertNotificationSchema>;

export type UserNotificationSettingsDb = typeof userNotificationSettings.$inferSelect;
export type InsertUserNotificationSettings = z.infer<typeof insertUserNotificationSettingsSchema>;

export type AttendanceDb = typeof attendance.$inferSelect;
export type InsertAttendance = z.infer<typeof insertAttendanceSchema>;

export type MessageDb = typeof messages.$inferSelect;
export type InsertMessage = z.infer<typeof insertMessageSchema>;

export type DocumentDb = typeof documents.$inferSelect;
export type InsertDocument = z.infer<typeof insertDocumentSchema>;

export type NotificationType = "event_reminder" | "task_assigned" | "task_updated" | "file_invitation" | "general";
export type AttendanceStatus = "present" | "absent" | "excused" | "late";

export type FileRole = "manager" | "deputy" | "member";
export type TaskStatus = "pending" | "in_progress" | "completed" | "cancelled";

export const fileRoleNames: Record<FileRole, string> = {
  manager: "مسؤول الملف",
  deputy: "نائب المسؤول",
  member: "عضو",
};

export const taskStatusNames: Record<TaskStatus, string> = {
  pending: "قيد الانتظار",
  in_progress: "قيد التنفيذ",
  completed: "مكتملة",
  cancelled: "ملغاة",
};

export const attendanceStatusNames: Record<AttendanceStatus, string> = {
  present: "حاضر",
  absent: "غائب",
  excused: "معذور",
  late: "متأخر",
};
